### ISSUE TITLE
About

### ISSUE THREAD

**Issue by devbn3li** [dragonsbootcampllc/DraagonsWebsite24#34]
![image](https://github.com/dragonsbootcampllc/DraagonsWebsite24/assets/76428295/b66a0166-0d86-4350-a7ce-efa09af59bb9)

**Comment by devbn3li** [comment]
![image](https://github.com/dragonsbootcampllc/DraagonsWebsite24/assets/76428295/a2352efe-306e-4726-9dac-564cf58f4539)

any text we will replace it later

**Comment by Hamdysaad20** [comment]
https://www.canva.com/design/DAF-MM54ui4/OdAtPGMf0QfP6zJe-4R9ZA/edit?utm_content=DAF-MM54ui4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Hamdysaad20** [comment]
Notes: 

- Use the Hero that is the same with all pages
- use the link to get all data about dragons 
- customized it with GPT and make sure to give you a simple short CTA text
