### ISSUE TITLE
Student Activity Page

### ISSUE THREAD

**Issue by Hamdysaad20** [dragonsbootcampllc/DraagonsWebsite24#44]

**Comment by devbn3li** [comment]
![image](https://github.com/dragonsbootcampllc/DraagonsWebsite24/assets/76428295/a95dae2c-da12-4d07-8272-caa8ee809b55)

join our student activity to prepare yourself for real-life jobs!

**Comment by devbn3li** [comment]
![image](https://github.com/dragonsbootcampllc/DraagonsWebsite24/assets/76428295/13dce800-beb6-4617-b498-216475609a7c)
use this component for the current content

**Comment by devbn3li** [comment]
- add slider that shows our student activity partners like GDSC , Microsoft Ambassadors, ... etc
- finaly CTA
