### ISSUE TITLE
 For Students Page

### ISSUE THREAD

**Issue by Hamdysaad20** [dragonsbootcampllc/DraagonsWebsite24#47]

**Comment by devbn3li** [comment]
![image](https://github.com/dragonsbootcampllc/DraagonsWebsite24/assets/76428295/cc9f1eff-1a07-4ab0-a729-62c16e243ca9)

**Comment by devbn3li** [comment]
![image](https://github.com/dragonsbootcampllc/DraagonsWebsite24/assets/76428295/bd539261-fd52-4652-8da0-c45b8766ae7d)

same compo

**Comment by devbn3li** [comment]
![image](https://github.com/dragonsbootcampllc/DraagonsWebsite24/assets/76428295/24c1cba8-c917-4ee0-bd42-3e3dcd815c29)

and this

**Comment by devbn3li** [comment]
For creativity make CTA to make them apply 
this is the real task for youuuuuuuu
