### ISSUE TITLE
 Get Talents Page

### ISSUE THREAD

**Issue by Hamdysaad20** [dragonsbootcampllc/DraagonsWebsite24#51]

**Comment by devbn3li** [comment]
![image](https://github.com/dragonsbootcampllc/DraagonsWebsite24/assets/76428295/d7c163bd-e375-45e0-8e22-9b526c672898)

get the best of our talents and boost your progress!

**Comment by devbn3li** [comment]
![image](https://github.com/dragonsbootcampllc/DraagonsWebsite24/assets/76428295/cec9dd57-fddc-43ae-ad64-7b24f2dacadc)

**Comment by devbn3li** [comment]
![image](https://github.com/dragonsbootcampllc/DraagonsWebsite24/assets/76428295/ae366b42-8940-45f0-976b-87c3318f420b)

**Comment by devbn3li** [comment]
![image](https://github.com/dragonsbootcampllc/DraagonsWebsite24/assets/76428295/b1b21418-6a6f-438d-9007-05b44764734c)
